// Generated by CoffeeScript 1.9.1
(function() {
  var Model,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Model = (function() {
    Util.Export(Model, 'test/app/Model');

    function Model(app, stream, rest) {
      this.app = app;
      this.stream = stream;
      this.rest = rest;
      this.errorsDetected = bind(this.errorsDetected, this);
      this.onMilePostsError = bind(this.onMilePostsError, this);
      this.onTownForecastError = bind(this.onTownForecastError, this);
      this.onForecastsError = bind(this.onForecastsError, this);
      this.onDealsError = bind(this.onDealsError, this);
      this.onConditionsError = bind(this.onConditionsError, this);
      this.onSegmentsError = bind(this.onSegmentsError, this);
      this.doTownForecast = bind(this.doTownForecast, this);
      this.doForecasts = bind(this.doForecasts, this);
      this.doMilePosts = bind(this.doMilePosts, this);
      this.doDeals = bind(this.doDeals, this);
      this.doConditions = bind(this.doConditions, this);
      this.doSegments = bind(this.doSegments, this);
      this.checkComplete = bind(this.checkComplete, this);
    }

    Model.prototype.ready = function() {
      return this.subscribe();
    };

    Model.prototype.subscribe = function() {
      this.stream.subscribe('Source', (function(_this) {
        return function(object) {
          return _this.onSource(object.content);
        };
      })(this));
      return this.stream.subscribe('Destination', (function(_this) {
        return function(object) {
          return _this.onDestination(object.content);
        };
      })(this));
    };

    Model.prototype.resetCompletionStatus = function() {};

    Model.prototype.createTrip = function(source, destination) {};

    Model.prototype.doTrip = function(trip) {};

    Model.prototype.doTripLocal = function(trip) {};

    Model.prototype.checkComplete = function() {};

    Model.prototype.launchTrip = function(trip) {};

    Model.prototype.restForecasts = function(trip) {};

    Model.prototype.doSegments = function(args, segments) {};

    Model.prototype.doConditions = function(args, conditions) {};

    Model.prototype.doDeals = function(args, deals) {};

    Model.prototype.doMilePosts = function(args, milePosts) {};

    Model.prototype.doForecasts = function(args, forecasts) {};

    Model.prototype.doTownForecast = function(args, forecast) {};

    Model.prototype.onSegmentsError = function(obj) {};

    Model.prototype.onConditionsError = function(obj) {};

    Model.prototype.onDealsError = function(obj) {};

    Model.prototype.onForecastsError = function(obj) {};

    Model.prototype.onTownForecastError = function(obj) {};

    Model.prototype.pushForecastsWhenComplete = function(forecasts) {};

    Model.prototype.onMilePostsError = function(obj) {};

    Model.prototype.errorsDetected = function() {};

    return Model;

  })();

}).call(this);
