// Generated by CoffeeScript 1.9.1
(function() {
  var Rest;

  Rest = (function() {
    Util.Export(Rest, 'test/app/Rest');

    function Rest(app, stream) {
      this.app = app;
      this.stream = stream;
    }

    Rest.prototype.segmentsFromLocal = function(direction, onSuccess, onError) {};

    Rest.prototype.conditionsFromLocal = function(direction, onSuccess, onError) {};

    Rest.prototype.dealsFromLocal = function(direction, onSuccess, onError) {};

    Rest.prototype.milePostsFromLocal = function(onSuccess, onError) {};

    Rest.prototype.forecastsFromLocal = function(onSuccess, onError) {};

    Rest.prototype.segmentsByPreset = function(preset, onSuccess, onError) {};

    Rest.prototype.conditionsBySegments = function(segments, onSuccess, onError) {};

    Rest.prototype.deals = function(latlon, segments, onSuccess, onError) {};

    Rest.prototype.forecastByTown = function(name, town, onSuccess, onError) {};

    Rest.prototype.getForecast = function(args, onSuccess, onError) {};

    Rest.prototype.forecastByLatLonTime = function(lat, lon, time, onSuccess, onError) {};

    Rest.prototype.requestSegmentsBy = function(query, onSuccess, onError) {
      Util.noop('Stream.requestSegmentsBy', query, onSuccess, onError);
    };

    Rest.prototype.requestConditionsBy = function(query, onSuccess, onError) {
      Util.noop('Stream.requestConditionsBy', query, onSuccess, onError);
    };

    Rest.prototype.requestDealsBy = function(query, onSuccess, onError) {
      Util.noop('Stream.requestDealsBy', query, onSuccess, onError);
    };

    Rest.prototype.segmentsByLatLon = function(slat, slon, elat, elon, onSuccess, onError) {};

    Rest.prototype.segmentsBySegments = function(segments, onSuccess, onError) {};

    Rest.prototype.conditionsBySegmentsDate = function(segments, date, onSuccess, onError) {};

    Rest.prototype.dealsByUrl = function(url, onSuccess, onError) {};

    Rest.prototype.toCsv = function(array) {};

    Rest.prototype.segIdNum = function(segment) {};

    return Rest;

  })();

}).call(this);
