// Generated by CoffeeScript 1.9.1
(function() {
  var Advisory;

  Advisory = (function() {
    Util.Export(Advisory, 'ui/Advisory');

    function Advisory(app, stream) {
      this.app = app;
      this.stream = stream;
    }

    Advisory.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    Advisory.prototype.html = function() {
      return "<div id=\"" + (this.app.id('Advisory')) + "\" class=\"" + (this.app.css('Advisory')) + "\"></div>";
    };

    Advisory.prototype.layout = function() {};

    Advisory.prototype.show = function() {};

    Advisory.prototype.hide = function() {};

    return Advisory;

  })();

}).call(this);
