// Generated by CoffeeScript 1.9.1
(function() {
  var Advisory;

  Advisory = (function() {
    Util.Export(Advisory, 'ui/Advisory');

    function Advisory(app, stream) {
      this.app = app;
      this.stream = stream;
    }

    Advisory.prototype.ready = function() {
      this.$ = $(this.html());
      return this.subscribe();
    };

    Advisory.prototype.subscribe = function() {
      this.stream.subscribe('Location', (function(_this) {
        return function(object) {
          return _this.onLocation(object.content);
        };
      })(this));
      return this.stream.subscribe('Orient', (function(_this) {
        return function(object) {
          return _this.layout(object.content);
        };
      })(this));
    };

    Advisory.prototype.onLocation = function(latlon) {
      return Util.log('Advisory.onLocation()', this.ext, latlon);
    };

    Advisory.prototype.layout = function(orientation) {
      return Util.log('Advisory.layout()', orientation);
    };

    Advisory.prototype.html = function() {
      return "<div id=\"" + (this.app.id('Advisory')) + "\" class=\"" + (this.app.css('Advisory')) + "\"></div>";
    };

    Advisory.prototype.show = function() {};

    Advisory.prototype.hide = function() {};

    return Advisory;

  })();

}).call(this);
