// Generated by CoffeeScript 1.9.1
(function() {
  var Deals;

  Deals = (function() {
    Util.Export(Deals, 'ui/Deals');

    function Deals(app, model) {
      this.app = app;
      this.model = model;
    }

    Deals.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    Deals.prototype.html = function() {
      return "<div id=\"" + (this.app.id('Deals')) + "\" class=\"" + (this.app.css('Deals')) + "\"></div>";
    };

    Deals.prototype.layout = function() {};

    Deals.prototype.show = function() {};

    Deals.prototype.hide = function() {};

    return Deals;

  })();

}).call(this);
