// Generated by CoffeeScript 1.9.1
(function() {
  var Destination;

  Destination = (function() {
    Util.Export(Destination, 'ui/Destination');

    function Destination(app, stream, go, nogo, threshold) {
      this.app = app;
      this.stream = stream;
      this.go = go;
      this.nogo = nogo;
      this.threshold = threshold;
    }

    Destination.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    Destination.prototype.html = function() {
      return "<div id=\"" + (this.app.id('Destination')) + "\" class=\"" + (this.app.css('Destination')) + "\">Destination</div>";
    };

    Destination.prototype.layout = function() {};

    Destination.prototype.show = function() {
      return this.$.show();
    };

    Destination.prototype.hide = function() {
      return this.$.hide();
    };

    return Destination;

  })();

}).call(this);
