// Generated by CoffeeScript 1.9.1
(function() {
  var Go;

  Go = (function() {
    Util.Export(Go, 'ui/Go');

    function Go(app, stream) {
      var DriveBar;
      this.app = app;
      this.stream = stream;
      DriveBar = Util.Import('ui/DriveBar');
      this.driveBar = new DriveBar(this.app, this.stream, 'Go');
      this.first = true;
    }

    Go.prototype.ready = function() {
      this.$ = $(this.html());
      this.$GoBanner = this.$.find('#GoBanner');
      this.$GoBannerText = this.$.find('#GoBannerText');
      return this.subscribe();
    };

    Go.prototype.subscribe = function() {
      this.stream.subscribe('Orient', (function(_this) {
        return function(object) {
          return _this.layout(object.content);
        };
      })(this));
      return this.stream.subscribe('Deals', (function(_this) {
        return function(object) {
          return _this.onDeals(object.content);
        };
      })(this));
    };

    Go.prototype.layout = function(orientation) {
      Util.log('Go.layout()', orientation);
      return this.goSize();
    };

    Go.prototype.onDeals = function(deals) {
      var deal, i, len, results;
      results = [];
      for (i = 0, len = deals.length; i < len; i++) {
        deal = deals[i];
        results.push(Util.log('Go.onDeals()', deal));
      }
      return results;
    };

    Go.prototype.html = function() {
      return "<div id=\"" + (this.app.id('Go')) + "\"         class=\"" + (this.app.css('Go')) + "\">\n  <div   id=\"" + (this.app.id('GoBanner')) + "\"     class=\"" + (this.app.css('GoBanner')) + "\">\n    <div id=\"" + (this.app.id('GoBannerText')) + "\" class=\"" + (this.app.css('GoBannerText')) + "\">GO</div>\n  </div>\n  <div id=\"" + (this.app.id('GoDeals')) + "\"  class=\"" + (this.app.css('GoDeals')) + "\">\n    <div>11 deals at your destination</div>\n    <div>get going to beat traffic!</div>\n  </div>\n  <div id=\"" + (this.app.id('GoDrive')) + "\" class=\"" + (this.app.css('GoDrive')) + "\">" + (this.driveBar.html('Go')) + "</div>\n</div>";
    };

    Go.prototype.postReady = function() {
      this.driveBar.postReady();
      return this.goSize();
    };

    Go.prototype.goSize = function() {
      var fontSize;
      fontSize = this.first ? this.app.height() * this.$GoBanner.height() * 0.0065 : this.$GoBanner.height() * 0.65;
      Util.log('@$GoBanner.height()', {
        ah: this.app.height(),
        gh: this.$GoBanner.height(),
        fs: fontSize
      });
      this.$GoBannerText.css({
        fontSize: fontSize + 'px'
      });
      return this.first = false;
    };

    Go.prototype.show = function() {
      return this.$.show();
    };

    Go.prototype.hide = function() {
      return this.$.hide();
    };

    return Go;

  })();

}).call(this);
