// Generated by CoffeeScript 1.9.1
(function() {
  var Go;

  Go = (function() {
    Util.Export(Go, 'ui/Go');

    function Go(app, stream) {
      var DriveBar;
      this.app = app;
      this.stream = stream;
      DriveBar = Util.Import('ui/DriveBar');
      this.driveBar = new DriveBar(this.app, this.stream, 'Go');
    }

    Go.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    Go.prototype.html = function() {
      return "<div id=\"" + (this.app.id('Go')) + "\"         class=\"" + (this.app.css('Go')) + "\">\n  <div   id=\"" + (this.app.id('GoBanner')) + "\"     class=\"" + (this.app.css('GoBanner')) + "\">\n    <div id=\"" + (this.app.id('GoBannerText')) + "\" class=\"" + (this.app.css('GoBannerText')) + "\">GO</div>\n  </div>\n  <div id=\"" + (this.app.id('GoDeals')) + "\"  class=\"" + (this.app.css('GoDeals')) + "\">\n    <div>11 deals at your destination</div>\n    <div>get going to beat traffic!</div>\n  </div>\n  <div id=\"" + (this.app.id('GoDrive')) + "\" class=\"" + (this.app.css('GoDrive')) + "\">" + (this.driveBar.html('Go')) + "</div>\n</div>";
    };

    Go.prototype.postReady = function() {
      return this.driveBar.postReady();
    };

    Go.prototype.layout = function() {};

    Go.prototype.show = function() {
      return this.$.show();
    };

    Go.prototype.hide = function() {
      return this.$.hide();
    };

    return Go;

  })();

}).call(this);
