// Generated by CoffeeScript 1.9.1
(function() {
  var GoUI;

  GoUI = (function() {
    Util.Export(GoUI, 'ui/GoUI');

    function GoUI(app, stream) {
      var DriveBar;
      this.app = app;
      this.stream = stream;
      DriveBar = Util.Import('ui/DriveBar');
      this.driveBar = new DriveBar(this.app, this.stream, 'Go', this, 'Portrait');
      this.first = true;
    }

    GoUI.prototype.ready = function() {
      this.$ = $(this.html());
      this.$GoBanner = this.$.find('#GoBanner');
      this.$GoBannerText = this.$.find('#GoBannerText');
      this.$GoDeals = this.$.find('#GoDeals');
      return this.driveBar.ready();
    };

    GoUI.prototype.position = function() {
      this.driveBar.position();
      this.goSize();
      return this.subscribe();
    };

    GoUI.prototype.html = function() {
      return "<div id=\"" + (this.app.id('Go')) + "\"         class=\"" + (this.app.css('Go')) + "\">\n  <div   id=\"" + (this.app.id('GoBanner')) + "\"     class=\"" + (this.app.css('GoBanner')) + "\">\n    <div id=\"" + (this.app.id('GoBannerText')) + "\" class=\"" + (this.app.css('GoBannerText')) + "\">GO</div>\n  </div>\n  <div id=\"" + (this.app.id('GoDeals')) + "\"  class=\"" + (this.app.css('GoDeals')) + "\">\n    <div>11 deals at your destination</div>\n    <div>get going to beat traffic!</div>\n  </div>\n  <div id=\"" + (this.app.id('GoDrive')) + "\" class=\"" + (this.app.css('GoDrive')) + "\">" + (this.driveBar.html('Go')) + "</div>\n</div>";
    };

    GoUI.prototype.subscribe = function() {
      this.stream.subscribe('Orient', (function(_this) {
        return function(object) {
          return _this.layout(object.content);
        };
      })(this));
      return this.stream.subscribe('Deals', (function(_this) {
        return function(object) {
          return _this.onDeals(object.content);
        };
      })(this));
    };

    GoUI.prototype.layout = function(orientation) {
      Util.dbg('Go.layout()', orientation);
      return this.goSize();
    };

    GoUI.prototype.onDeals = function(deals) {
      var html;
      this.$GoDeals.empty();
      html = this.app.deals.goDealsHtml(deals);
      return this.$GoDeals.append(html);
    };

    GoUI.prototype.goSize = function() {
      var fontSize;
      fontSize = this.first ? this.app.height() * this.$GoBanner.height() * 0.0065 : this.$GoBanner.height() * 0.65;
      this.$GoBannerText.css({
        fontSize: fontSize + 'px'
      });
      return this.first = false;
    };

    GoUI.prototype.show = function() {
      return this.$.show();
    };

    GoUI.prototype.hide = function() {
      return this.$.hide();
    };

    return GoUI;

  })();

}).call(this);
