// Generated by CoffeeScript 1.9.1
(function() {
  var Navigate;

  Navigate = (function() {
    Util.Export(Navigate, 'ui/Navigate');

    function Navigate(app, model) {
      this.app = app;
      this.model = model;
    }

    Navigate.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    Navigate.prototype.html = function() {
      return "<div id=\"" + (this.app.id('Navigate')) + "\" class=\"" + (this.app.css('Navigate')) + "\"></div>";
    };

    Navigate.prototype.layout = function() {};

    show;

    (function() {});

    Navigate.prototype.hide = function() {};

    return Navigate;

  })();

}).call(this);
