// Generated by CoffeeScript 1.9.1
(function() {
  var Navigate;

  Navigate = (function() {
    Util.Export(Navigate, 'ui/Navigate');

    function Navigate(app, stream) {
      this.app = app;
      this.stream = stream;
    }

    Navigate.prototype.ready = function() {
      this.$ = $(this.html());
      return this.subscribe();
    };

    Navigate.prototype.subscribe = function() {
      return this.stream.subscribe('Orient', (function(_this) {
        return function(object) {
          return _this.layout(object.content);
        };
      })(this));
    };

    Navigate.prototype.layout = function(orientation) {
      return Util.log('Navigate.layout()', orientation);
    };

    Navigate.prototype.html = function() {
      return "<div id=\"" + (this.app.id('Navigate')) + "\" class=\"" + (this.app.css('Navigate')) + "\">Navigate</div>";
    };

    Navigate.prototype.show = function() {
      return this.$.show();
    };

    Navigate.prototype.hide = function() {
      return this.$.hide();
    };

    return Navigate;

  })();

}).call(this);
