// Generated by CoffeeScript 1.9.1
(function() {
  var NoGo;

  NoGo = (function() {
    Util.Export(NoGo, 'ui/NoGo');

    function NoGo(app, stream) {
      var DriveBar;
      this.app = app;
      this.stream = stream;
      DriveBar = Util.Import('ui/DriveBar');
      this.driveBar = new DriveBar(this.app, this.stream, 'NoGo');
    }

    NoGo.prototype.ready = function() {
      this.$ = $(this.html());
      return this.subscribe();
    };

    NoGo.prototype.subscribe = function() {
      this.stream.subscribe('Orient', (function(_this) {
        return function(object) {
          return _this.layout(object.content);
        };
      })(this));
      return this.stream.subscribe('Deals', (function(_this) {
        return function(object) {
          return _this.onDeals(object.content);
        };
      })(this));
    };

    NoGo.prototype.layout = function(orientation) {
      return Util.log('NoGo.layout()', orientation);
    };

    NoGo.prototype.onDeals = function(deals) {
      var deal, i, len, results;
      results = [];
      for (i = 0, len = deals.length; i < len; i++) {
        deal = deals[i];
        results.push(Util.log('NoGo.onDeals()', deal));
      }
      return results;
    };

    NoGo.prototype.html = function() {
      return "<div      id=\"" + (this.app.id('NoGo')) + "\"          class=\"" + (this.app.css('NoGo')) + "\">\n  <div   id=\"" + (this.app.id('NoGoBanner')) + "\"     class=\"" + (this.app.css('NoGoBanner')) + "\">\n    <div id=\"" + (this.app.id('NoGoBannerText')) + "\" class=\"" + (this.app.css('NoGoBannerText')) + "\">NO GO</div>\n  </div>\n  <div id=\"" + (this.app.id('NoGoODeals')) + "\"       class=\"" + (this.app.css('NoGoDeals')) + "\">\n    <div>50% off Hotel</div>\n  </div>\n  <div id=\"" + (this.app.id('NoGoDrive')) + "\" class=\"" + (this.app.css('NoGoDrive')) + "\">" + (this.driveBar.html('NoGo')) + "</div>\n</div>";
    };

    NoGo.prototype.postReady = function() {
      return this.driveBar.postReady();
    };

    NoGo.prototype.show = function() {
      return this.$.show();
    };

    NoGo.prototype.hide = function() {
      return this.$.hide();
    };

    return NoGo;

  })();

}).call(this);
