// Generated by CoffeeScript 1.9.1
(function() {
  var NoGo;

  NoGo = (function() {
    Util.Export(NoGo, 'ui/NoGo');

    function NoGo(app, stream) {
      var DriveBar;
      this.app = app;
      this.stream = stream;
      DriveBar = Util.Import('ui/DriveBar');
      this.driveBar = new DriveBar(this.app, this.stream, 'NoGo');
    }

    NoGo.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    NoGo.prototype.html = function() {
      return "<div      id=\"" + (this.app.id('NoGo')) + "\"          class=\"" + (this.app.css('NoGo')) + "\">\n  <div   id=\"" + (this.app.id('NoGoBanner')) + "\"     class=\"" + (this.app.css('NoGoBanner')) + "\">\n    <div id=\"" + (this.app.id('NoGoBannerText')) + "\" class=\"" + (this.app.css('NoGoBannerText')) + "\">NO GO</div>\n  </div>\n  <div id=\"" + (this.app.id('NoGoODeals')) + "\"       class=\"" + (this.app.css('NoGoDeals')) + "\">\n    <div>50% off Hotel</div>\n  </div>\n  <div id=\"" + (this.app.id('NoGoDrive')) + "\" class=\"" + (this.app.css('NoGoDrive')) + "\">" + (this.driveBar.html('NoGo')) + "</div>\n</div>";
    };

    NoGo.prototype.postReady = function() {
      return this.driveBar.postReady();
    };

    NoGo.prototype.layout = function() {};

    NoGo.prototype.show = function() {
      return this.$.show();
    };

    NoGo.prototype.hide = function() {
      return this.$.hide();
    };

    return NoGo;

  })();

}).call(this);
