// Generated by CoffeeScript 1.9.1
(function() {
  var RoadUI;

  RoadUI = (function() {
    Util.Export(RoadUI, 'ui/RoadUI');

    function RoadUI(app, stream) {
      var DriveBar;
      this.app = app;
      this.stream = stream;
      DriveBar = Util.Import('ui/DriveBar');
      this.driveBar = new DriveBar(this.app, this.stream, 'Road', this, 'Landscape');
    }

    RoadUI.prototype.ready = function() {
      this.$ = $(this.html());
      return this.driveBar.ready();
    };

    RoadUI.prototype.position = function() {
      this.driveBar.position();
      return this.subscribe();
    };

    RoadUI.prototype.subscribe = function() {
      return this.stream.subscribe('Orient', (function(_this) {
        return function(object) {
          return _this.layout(object.content);
        };
      })(this));
    };

    RoadUI.prototype.html = function() {
      return "<div id=\"" + (this.app.id('Road')) + "\" class=\"" + (this.app.css('Road')) + "\">" + (this.driveBar.html('Trip')) + "</div>";
    };

    RoadUI.prototype.layout = function(orientation) {
      Util.dbg('Road.layout()', orientation);
      return this.driveBar.layout(orientation);
    };

    return RoadUI;

  })();

}).call(this);
