// Generated by CoffeeScript 1.9.1
(function() {
  var Road;

  Road = (function() {
    Util.Export(Road, 'ui/Road');

    function Road(app, stream) {
      var DriveBar;
      this.app = app;
      this.stream = stream;
      DriveBar = Util.Import('ui/DriveBar');
      this.driveBar = new DriveBar(this.app, this.stream, 'Road');
    }

    Road.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    Road.prototype.html = function() {
      return "<div id=\"" + (this.app.id('Road')) + "\" class=\"" + (this.app.css('Road')) + "\">" + (this.driveBar.html('Trip')) + "</div>";
    };

    Road.prototype.postReady = function() {
      return this.driveBar.postReady();
    };

    Road.prototype.layout = function(orientation) {
      return this.driveBar.layout(orientation);
    };

    Road.prototype.show = function() {
      return this.$.show();
    };

    Road.prototype.hide = function() {
      return this.$.hide();
    };

    return Road;

  })();

}).call(this);
