// Generated by CoffeeScript 1.9.1
(function() {
  var Threshold;

  Threshold = (function() {
    Util.Export(Threshold, 'ui/Threshold');

    function Threshold(app, model) {
      this.app = app;
      this.model = model;
    }

    Threshold.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    Threshold.prototype.html = function() {
      return "<div id=\"" + (this.app.id('Threshold')) + "\"       class=\"" + (this.app.css('Threshold')) + "\">\n   <div id=\"" + (this.app.id('ThresholdAdjust')) + "\" class=\"" + (this.app.css('ThresholdAdjust')) + "\">Adjust Threshold</div>\n   <img src=\"img/app/Threshold.png\">\n</div>";
    };

    Threshold.prototype.layout = function(orientation) {
      return Util.noop(orientation);
    };

    Threshold.prototype.show = function() {
      return this.$.show();
    };

    Threshold.prototype.hide = function() {
      return this.$.hide();
    };

    return Threshold;

  })();

}).call(this);
