// Generated by CoffeeScript 1.9.1
(function() {
  var Trip;

  Trip = (function() {
    Util.Export(Trip, 'ui/Trip');

    function Trip(app, stream, road, weather, advisory) {
      this.app = app;
      this.stream = stream;
      this.road = road;
      this.weather = weather;
      this.advisory = advisory;
      this.Data = Util.Import('app/Data');
      this.driveBarsCreated = false;
    }

    Trip.prototype.ready = function() {
      this.advisory.ready();
      this.road.ready();
      this.weather.ready();
      this.$ = $(this.html());
      this.$.append(this.advisory.$);
      this.$.append(this.weather.$);
      return this.$.append(this.road.$);
    };

    Trip.prototype.postReady = function() {
      this.road.postReady();
      this.weather.postReady();
      this.advisory.postReady();
      return this.subscribe();
    };

    Trip.prototype.subscribe = function() {
      return this.stream.subscribe('Orient', (function(_this) {
        return function(object) {
          return _this.layout(object.content);
        };
      })(this));
    };

    Trip.prototype.layout = function(orientation) {
      this.road.layout(orientation);
      this.weather.layout(orientation);
      return this.advisory.layout(orientation);
    };

    Trip.prototype.html = function() {
      return "<div id=\"" + (this.app.id('Trip')) + "\" class=\"" + (this.app.css('Trip')) + "\"></div>";
    };

    Trip.prototype.show = function() {
      return this.$.show();
    };

    Trip.prototype.hide = function() {
      return this.$.hide();
    };

    return Trip;

  })();

}).call(this);
