// Generated by CoffeeScript 1.9.1
(function() {
  var UI;

  UI = (function() {
    Util.Export(Trip, 'ui/UI');

    function UI(app, login, destination1, trip1, deals1, navigate1) {
      this.app = app;
      this.login = login;
      this.destination = destination1;
      this.trip = trip1;
      this.deals = deals1;
      this.navigate = navigate1;
    }

    UI.prototype.ready = function() {
      this.$ = $(this.html());
      $('#App').append(this.$);
      this.$view = this.$.find('#View');
      this.$view.append(destination.$);
      this.$view.append(trip.$);
      this.$view.append(deals.$);
      this.$view.append(navigate.$);
      this.$destinationIcon = this.$.find('DestinationIcon');
      this.$tripIcon = this.$.find('TripIcon');
      this.$dealIcon = this.$.find('DealIcon');
      return this.$namigateIcon = this.$.find('NavigateIcon');
    };

    UI.prototype.id = function(name, type) {
      return this.app.id(name, type);
    };

    UI.prototype.css = function(name, type) {
      return this.app.css(name, type);
    };

    UI.prototype.icon = function(name, type, fa) {
      return this.app.icon(name, type, fa);
    };

    UI.prototype.html = function() {
      return "<div    id=\"" + (this.id('UI')) + "\"                  class=\"" + (this.css('UI')) + "\">\n <div  id=\"" + (this.id('Icons')) + "\"               class=\"" + (this.css('Icons')) + "\">\n    <i id=\"" + (this.id('Destination', 'Icon')) + "\"  class=\"" + (this.icon('Destination', 'Icon', 'globe')) + "\">></i>\n    <i id=\"" + (this.id('Trip', 'Icon')) + "\"  class=\"" + (this.icon('Trip', 'Icon', 'car')) + "\">></i>\n    <i id=\"" + (this.id('Deals', 'Icon')) + "\"  class=\"" + (this.icon('Deals', 'Icon', 'road')) + "\">></i>\n    <i id=\"" + (this.id('Navigate', 'Icon')) + "\"  class=\"" + (this.icon('Navigate', 'Icon', 'long-arrow-right')) + "\">></i>\n </div>\n <div> id=\"" + (this.id('View')) + "\"   class=\"" + (this.css('View')) + "\"></div>\n</div>";
    };

    UI.prototype.layout = function() {};

    show;

    (function() {});

    UI.prototype.hide = function() {};

    return UI;

  })();

}).call(this);
