// Generated by CoffeeScript 1.9.1
(function() {
  var UI;

  UI = (function() {
    Util.Export(UI, 'ui/UI');

    function UI(app, destination, trip, deals, navigate) {
      this.app = app;
      this.destination = destination;
      this.trip = trip;
      this.deals = deals;
      this.navigate = navigate;
    }

    UI.prototype.ready = function() {
      this.$ = $(this.html());
      $('#App').append(this.$);
      this.$view = this.$.find('#View');
      this.$view.append(this.destination.$);
      this.$view.append(this.trip.$);
      this.$view.append(this.deals.$);
      this.$view.append(this.navigate.$);
      this.$destinationIcon = this.$.find('DestinationIcon');
      this.$tripIcon = this.$.find('TripIcon');
      this.$dealIcon = this.$.find('DealIcon');
      return this.$namigateIcon = this.$.find('NavigateIcon');
    };

    UI.prototype.id = function(name, type) {
      return this.app.id(name, type);
    };

    UI.prototype.css = function(name, type) {
      return this.app.css(name, type);
    };

    UI.prototype.icon = function(name, type, fa) {
      return this.app.icon(name, type, fa);
    };

    UI.prototype.html = function() {
      return "<div    id=\"" + (this.id('UI')) + "\"                  class=\"" + (this.css('UI')) + "\">\n <div  id=\"" + (this.id('Icons')) + "\"               class=\"" + (this.css('Icons')) + "\">\n    <i id=\"" + (this.id('Destination', 'Icon')) + "\"  class=\"" + (this.icon('Destination', 'Icon', 'map-marker')) + "\"></i>\n    <i id=\"" + (this.id('Trip', 'Icon')) + "\"  class=\"" + (this.icon('Trip', 'Icon', 'road')) + "\"></i>\n    <i id=\"" + (this.id('Deals', 'Icon')) + "\"  class=\"" + (this.icon('Deals', 'Icon', 'thumbs-up')) + "\"></i>\n    <i id=\"" + (this.id('Navigate', 'Icon')) + "\"  class=\"" + (this.icon('Navigate', 'Icon', 'street-view')) + "\"></i>\n </div>\n <div id=\"" + (this.id('View')) + "\" class=\"" + (this.css('View')) + "\"></div>\n</div>";
    };

    UI.prototype.layout = function() {};

    UI.prototype.show = function() {};

    UI.prototype.hide = function() {};

    return UI;

  })();

}).call(this);
