// Generated by CoffeeScript 1.9.1
(function() {
  var Weather;

  Weather = (function() {
    Util.Export(Weather, 'ui/Weather');

    function Weather(app) {
      this.app = app;
    }

    Weather.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    Weather.prototype.html = function() {
      return "<div class=\"Weather\">\n<div class=\"Weather1\"><iframe id=\"forecast_embed\" type=\"text/html\" frameborder=\"1\" height=\"100%\" width=\"100%\"\nsrc=\"http://forecast.io/embed/#lon=-105.334724&lat=39.701735&name=Evergreen\"> </iframe></div>\n<div class=\"Weather2\"><iframe id=\"forecast_embed\" type=\"text/html\" frameborder=\"1\" height=\"100%\" width=\"100%\"\nsrc=\"http://forecast.io/embed/#lon=-105.654065&lat=39.759558&name=US40 Exit\">      </iframe></div>\n<div class=\"Weather3\"><iframe id=\"forecast_embed\" type=\"text/html\" frameborder=\"1\" height=\"100%\" width=\"100%\"\nsrc=\"http://forecast.io/embed/#lon=-105.891111&lat=39.681757&name=E Tunnel\">    </iframe></div>\n<div class=\"Weather4\"><iframe id=\"forecast_embed\" type=\"text/html\" frameborder=\"1\" height=\"100%\" width=\"100%\"\nsrc=\"http://forecast.io/embed/#lon=-105.878342&lat=39.692400&name=W Tunnel\">    </iframe></div>\n<div class=\"Weather5\"><iframe id=\"forecast_embed\" type=\"text/html\" frameborder=\"1\" height=\"100%\" width=\"100%\"\nsrc=\"http://forecast.io/embed/#lon=-106.072685&lat=39.624160&name=Silver\">   </iframe></div>\n<div class=\"Weather6\"><iframe id=\"forecast_embed\" type=\"text/html\" frameborder=\"1\" height=\"100%\" width=\"100%\"\nsrc=\"http://forecast.io/embed/#lon=-106.147382&lat=39.503512&name=Copper\">     </iframe></div>\n<div class=\"Weather7\"><iframe id=\"forecast_embed\" type=\"text/html\" frameborder=\"1\" height=\"100%\" width=\"100%\"\nsrc=\"http://forecast.io/embed/#lon=-106.216071&lat=39.531042&name=Vail Pass\">      </iframe></div>\n<div class=\"Weather8\"><iframe id=\"forecast_embed\" type=\"text/html\" frameborder=\"1\" height=\"100%\" width=\"100%\"\nsrc=\"http://forecast.io/embed/#lon=-106.378767&lat=39.644407&name=Vail\">           </iframe></div>\n</div>";
    };

    Weather.prototype.html2 = function() {
      return "<div id=\"" + (this.app.id('Weather')) + "\" class=\"" + (this.app.css('Weather')) + "\"></div>";
    };

    Weather.prototype.layout = function() {};

    Weather.prototype.show = function() {};

    Weather.prototype.hide = function() {};

    return Weather;

  })();

}).call(this);
