// Generated by CoffeeScript 1.9.1
(function() {
  var Weather;

  Weather = (function() {
    Util.Export(Road, 'ui/Weather');

    function Weather(app) {
      this.app = app;
    }

    Weather.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    Weather.prototype.html = function() {
      return "<div id=\"" + (this.app.id('Weather')) + "\" class=\"" + (this.app.css('Weather')) + "\"></div>";
    };

    Weather.prototype.layout = function() {};

    show;

    (function() {});

    Weather.prototype.hide = function() {};

    return Weather;

  })();

}).call(this);
