// Generated by CoffeeScript 1.9.1
(function() {
  var AdvisoryUI;

  AdvisoryUI = (function() {
    Util.Export(AdvisoryUI, 'ui/AdvisoryUI');

    function AdvisoryUI(stream) {
      this.stream = stream;
    }

    AdvisoryUI.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    AdvisoryUI.prototype.position = function(screen) {
      Util.noop(screen);
      return this.subscribe();
    };

    AdvisoryUI.prototype.subscribe = function() {
      this.stream.subscribe('Location', (function(_this) {
        return function(location) {
          return _this.onLocation(location);
        };
      })(this));
      return this.stream.subscribe('Screen', (function(_this) {
        return function(screen) {
          return _this.onScreen(screen);
        };
      })(this));
    };

    AdvisoryUI.prototype.onLocation = function(location) {
      return Util.noop('AdvisoryUI.onLocation()', this.ext, location);
    };

    AdvisoryUI.prototype.onScreen = function(screen) {
      return Util.noop('AdvisoryUI.screen()', screen);
    };

    AdvisoryUI.prototype.html = function() {
      return "<div id=\"" + (Util.id('Advisory')) + "\" class=\"" + (Util.css('Advisory')) + "\"></div>";
    };

    return AdvisoryUI;

  })();

}).call(this);
