// Generated by CoffeeScript 1.9.1
(function() {
  var NoGoUI;

  NoGoUI = (function() {
    Util.Export(NoGoUI, 'ui/NoGoUI');

    function NoGoUI(stream) {
      var DriveBarUI;
      this.stream = stream;
      DriveBarUI = Util.Import('ui/DriveBarUI');
      this.driveBarUI = new DriveBarUI(this.stream, 'NoGo', this);
    }

    NoGoUI.prototype.ready = function() {
      this.$ = $(this.html());
      this.$NoGoBanner = this.$.find('#NoGoBanner');
      this.$NoGoBannerText = this.$.find('#NoGoBannerText');
      this.$NoGoDeals = this.$.find('#NoGoDeals');
      return this.driveBarUI.ready();
    };

    NoGoUI.prototype.position = function(screen) {
      this.driveBarUI.position(screen);
      return this.subscribe();
    };

    NoGoUI.prototype.html = function() {
      return "<div      id=\"" + (Util.id('NoGo')) + "\"          class=\"" + (Util.css('NoGo')) + "\">\n  <div   id=\"" + (Util.id('NoGoBanner')) + "\"     class=\"" + (Util.css('NoGoBanner')) + "\">\n    <div id=\"" + (Util.id('NoGoBannerText')) + "\" class=\"" + (Util.css('NoGoBannerText')) + "\">NO GO</div>\n  </div>\n  <div id=\"" + (Util.id('NoGoDeals')) + "\"       class=\"" + (Util.css('NoGoDeals')) + "\">\n    <div>50% off Hotel</div>\n  </div>\n  <div id=\"" + (Util.id('NoGoDrive')) + "\" class=\"" + (Util.css('NoGoDrive')) + "\">" + (this.driveBarUI.html('NoGo')) + "</div>\n</div>";
    };

    NoGoUI.prototype.subscribe = function() {
      this.stream.subscribe('Screen', (function(_this) {
        return function(screen) {
          return _this.onScreen(screen);
        };
      })(this));
      return this.stream.subscribe('Deals', (function(_this) {
        return function(deals) {
          return _this.onDeals(deals);
        };
      })(this));
    };

    NoGoUI.prototype.onScreen = function(screen) {
      return Util.noop('NavigateUI.onScreen()', screen);
    };

    NoGoUI.prototype.onDeals = function(deals) {
      var html;
      return;
      this.$NoGoDeals.empty();
      html = this.app.deals.goDealsHtml(deals);
      return this.$NoGoDeals.append(html);
    };

    NoGoUI.prototype.noGoSize = function(screen) {
      var fontSize;
      fontSize = this.first ? screen.height * this.$NoGoBanner.height() * 0.0065 : this.$NoGoBanner.height() * 0.65;
      this.$NoGoBannerText.css({
        fontSize: fontSize + 'px'
      });
      return this.first = false;
    };

    NoGoUI.prototype.show = function() {
      return this.$.show();
    };

    NoGoUI.prototype.hide = function() {
      return this.$.hide();
    };

    return NoGoUI;

  })();

}).call(this);
