// Generated by CoffeeScript 1.9.1
(function() {
  var ThresholdUI;

  ThresholdUI = (function() {
    Util.Export(ThresholdUI, 'ui/ThresholdUI');

    function ThresholdUI(stream) {
      this.stream = stream;
    }

    ThresholdUI.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    ThresholdUI.prototype.position = function(screen) {
      Util.noop(screen);
      return this.subscribe();
    };

    ThresholdUI.prototype.subscribe = function() {
      return this.stream.subscribe('Screen', (function(_this) {
        return function(screen) {
          return _this.onScreen(screen);
        };
      })(this));
    };

    ThresholdUI.prototype.onScreen = function(screen) {
      return Util.noop('ThresholdUI.onScreen()', screen);
    };

    ThresholdUI.prototype.html = function() {
      return "<div id=\"" + (Util.id('Threshold')) + "\"       class=\"" + (Util.css('Threshold')) + "\">\n   <div id=\"" + (Util.id('ThresholdAdjust')) + "\" class=\"" + (Util.css('ThresholdAdjust')) + "\">Adjust Threshold</div>\n   <img src=\"css/img/app/Threshold.png\">\n</div>";
    };

    ThresholdUI.prototype.show = function() {
      return this.$.show();
    };

    ThresholdUI.prototype.hide = function() {
      return this.$.hide();
    };

    return ThresholdUI;

  })();

}).call(this);
