// Generated by CoffeeScript 1.9.1
(function() {
  var TripUI;

  TripUI = (function() {
    Util.Export(TripUI, 'ui/TripUI');

    function TripUI(stream) {
      var AdvisoryUC, DriveBarUC, WeatherUC;
      this.stream = stream;
      WeatherUC = Util.Import('uc/WeatherUC');
      AdvisoryUC = Util.Import('uc/AdvisoryUC');
      DriveBarUC = Util.Import('uc/DriveBarUC');
      this.weatherUC = new WeatherUC(this.stream, 'Trip', [0, 0, 100, 45], [0, 0, 100, 45]);
      this.advisoryUC = new AdvisoryUC(this.stream, 'Trip', [0, 45, 100, 10], [0, 45, 100, 10]);
      this.driveBarUC = new DriveBarUC(this.stream, 'Trip', [4, 55, 92, 45], [4, 55, 92, 45]);
    }

    TripUI.prototype.ready = function() {
      this.weatherUC.ready();
      this.advisoryUC.ready();
      this.driveBarUC.ready();
      this.$ = $(this.html());
      return this.$.append(this.weatherUC.$, this.advisoryUC.$, this.driveBarUC.$);
    };

    TripUI.prototype.position = function(screen) {
      this.weatherUC.position(screen);
      this.advisoryUC.position(screen);
      this.driveBarUC.position(screen);
      return this.subscribe();
    };

    TripUI.prototype.subscribe = function() {
      return this.stream.subscribe('Screen', (function(_this) {
        return function(screen) {
          return _this.onScreen(screen);
        };
      })(this));
    };

    TripUI.prototype.onScreen = function(screen) {
      return Util.noop('TripUI.onScreen()', screen);
    };

    TripUI.prototype.html = function() {
      return "<div id=\"" + (Util.id('TripUI')) + "\" class=\"" + (Util.css('TripUI')) + "\"></div>";
    };

    TripUI.prototype.show = function() {
      return this.$.show();
    };

    TripUI.prototype.hide = function() {
      return this.$.hide();
    };

    return TripUI;

  })();

}).call(this);
