// Generated by CoffeeScript 1.9.1
(function() {
  var TripUI;

  TripUI = (function() {
    Util.Export(TripUI, 'ui/TripUI');

    function TripUI(stream, roadUI, weatherUI, advisoryUI) {
      this.stream = stream;
      this.roadUI = roadUI;
      this.weatherUI = weatherUI;
      this.advisoryUI = advisoryUI;
      this.Data = Util.Import('app/Data');
      this.driveBarsCreated = false;
    }

    TripUI.prototype.ready = function() {
      this.advisoryUI.ready();
      this.roadUI.ready();
      this.weatherUI.ready();
      this.$ = $(this.html());
      this.$.append(this.advisoryUI.$);
      this.$.append(this.weatherUI.$);
      return this.$.append(this.roadUI.$);
    };

    TripUI.prototype.position = function(screen) {
      this.roadUI.position(screen);
      this.weatherUI.position(screen);
      this.advisoryUI.position(screen);
      return this.subscribe();
    };

    TripUI.prototype.subscribe = function() {
      return this.stream.subscribe('Screen', (function(_this) {
        return function(screen) {
          return _this.onScreen(screen);
        };
      })(this));
    };

    TripUI.prototype.onScreen = function(screen) {
      return Util.noop('TripUI.onScreen()', screen);
    };

    TripUI.prototype.html = function() {
      return "<div id=\"" + (Util.id('Trip')) + "\" class=\"" + (Util.css('Trip')) + "\"></div>";
    };

    TripUI.prototype.show = function() {
      return this.$.show();
    };

    TripUI.prototype.hide = function() {
      return this.$.hide();
    };

    return TripUI;

  })();

}).call(this);
