// Generated by CoffeeScript 1.9.1
var Test;

Test = (function() {
  var UI;

  UI = Util.Import('ui/UI');

  UI.Test = Test;

  Util.Export(UI.Test, 'ui/UI.Test');

  function Test(ui, trip, destinationUI, goUI, noGoUI, tripUI, navigateUI) {
    this.ui = ui;
    this.trip = trip;
    this.destinationUI = destinationUI;
    this.goUI = goUI;
    this.noGoUI = noGoUI;
    this.tripUI = tripUI;
    this.navigateUI = navigateUI;
    Util.log('UI.Test.constructor');
  }

  return Test;

})();
