// Generated by CoffeeScript 1.9.1
(function() {
  var Test;

  Test = (function() {
    var UI;

    UI = Util.Import('ui/UI');

    UI.Test = Test;

    Util.Export(UI.Test, 'ui/UI.Test');

    function Test(ui, adivsoryUI, dealsUI, destinationUI, driveBarUI, goUI, noGoUI, roadUI, thresholdUI, trip, weatherUI, navigateUI) {
      this.ui = ui;
      this.adivsoryUI = adivsoryUI;
      this.dealsUI = dealsUI;
      this.destinationUI = destinationUI;
      this.driveBarUI = driveBarUI;
      this.goUI = goUI;
      this.noGoUI = noGoUI;
      this.roadUI = roadUI;
      this.thresholdUI = thresholdUI;
      this.trip = trip;
      this.weatherUI = weatherUI;
      this.navigateUI = navigateUI;
    }

    return Test;

  })();

}).call(this);
