// Generated by CoffeeScript 1.9.1
(function() {
  var Simulate;

  Simulate = (function() {
    Util.Export(Simulate, 'app/Simulate');

    function Simulate(app) {
      this.app = app;
    }

    return Simulate;

  })();

}).call(this);
