// Generated by CoffeeScript 1.9.1
(function() {
  var Simulate;

  Simulate = (function() {
    Util.Export(Simulate, 'app/Simulate');

    function Simulate(app, stream) {
      this.app = app;
      this.stream = stream;
    }

    return Simulate;

  })();

}).call(this);
