// Generated by CoffeeScript 1.9.1
(function() {
  var Test;

  Test = (function() {
    Util.Export(Test, 'app/Test');

    function Test(app, stream) {
      this.app = app;
      this.stream = stream;
      this.rest();
    }

    Test.prototype.rest = function() {
      Util.log('Test.rest() ------------');
      this.rest = this.app.rest;
      this.segments = [31, 32, 33, 34, 272, 273, 36, 37, 39, 40, 41, 276, 277, 268, 269, 44, 45];
      this.rest.segmentsByPreset(1, this.rest.logSegments);
      this.rest.conditionsBySegments(this.segments, this.rest.logConditions);
      return this.rest.deals([39.644407, -106.378767], this.segments, this.rest.logDeals);
    };

    return Test;

  })();

}).call(this);
