// Generated by CoffeeScript 1.9.1
(function() {
  var Town;

  Town = (function() {
    Util.Export(Town, 'app/Town');

    Town.roles = ['Source', 'AlongTheWay', 'Destination'];

    function Town(trip, name1, role) {
      this.trip = trip;
      this.name = name1;
      this.role = role;
      this.Data = Util.Import('app/Data');
      this.mile = this.Data.DestinationsMile[name];
    }

    return Town;

  })();

}).call(this);
