// Generated by CoffeeScript 1.9.1
(function() {
  var AdvisoryUC;

  AdvisoryUC = (function() {
    Util.Export(AdvisoryUC, 'uc/AdvisoryUC');

    function AdvisoryUC(stream, role, port, land) {
      this.stream = stream;
      this.role = role;
      this.port = port;
      this.land = land;
    }

    AdvisoryUC.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    AdvisoryUC.prototype.position = function(screen) {
      this.onScreen(screen);
      return this.subscribe();
    };

    AdvisoryUC.prototype.subscribe = function() {
      this.stream.subscribe('Location', (function(_this) {
        return function(location) {
          return _this.onLocation(location);
        };
      })(this));
      return this.stream.subscribe('Screen', (function(_this) {
        return function(screen) {
          return _this.onScreen(screen);
        };
      })(this));
    };

    AdvisoryUC.prototype.onLocation = function(location) {
      return Util.noop('AdvisoryUC.onLocation()', this.ext, location);
    };

    AdvisoryUC.prototype.onScreen = function(screen) {
      return Util.cssPosition(this.$, screen, this.port, this.land);
    };

    AdvisoryUC.prototype.html = function() {
      return "<div id=\"" + (Util.id('AdvisoryUC', this.role)) + "\" class=\"" + (Util.css('AdvisoryUC')) + "\"></div>";
    };

    return AdvisoryUC;

  })();

}).call(this);
