// Generated by CoffeeScript 1.9.1
(function() {
  var BannerUC;

  BannerUC = (function() {
    Util.Export(BannerUC, 'uc/BannerUC');

    function BannerUC(stream, role, port, land) {
      this.stream = stream;
      this.role = role;
      this.port = port;
      this.land = land;
    }

    BannerUC.prototype.ready = function() {
      this.$ = $(this.html());
      return this.$bannerText = this.$.find('#BannerText');
    };

    BannerUC.prototype.position = function(screen) {
      this.onScreen(screen);
      return this.subscribe();
    };

    BannerUC.prototype.subscribe = function() {
      this.stream.subscribe('Location', (function(_this) {
        return function(location) {
          return _this.onLocation(location);
        };
      })(this));
      this.stream.subscribe('Screen', (function(_this) {
        return function(screen) {
          return _this.onScreen(screen);
        };
      })(this));
      return this.stream.subscribe('Trip', (function(_this) {
        return function(trip) {
          return _this.onTrip(trip);
        };
      })(this));
    };

    BannerUC.prototype.onLocation = function(location) {
      return Util.noop('BannerUC.onLocation()', this.ext, location);
    };

    BannerUC.prototype.onTrip = function(trip) {
      return this.changeRecommendation(trip.recommendation);
    };

    BannerUC.prototype.changeRecommendation = function(recommendation) {
      var klass, scale;
      this.$bannerText.text(recommendation);
      klass = recommendation === 'GO' ? 'GoBanner' : 'NoGoBanner';
      this.$.attr('class', klass);
      scale = this.screen.orientation === 'Portrait' ? this.port[3] : this.land[3];
      scale = recommendation === 'GO' ? scale * 0.0050 : scale * 0.0020;
      return this.$.css({
        fontSize: screen.height * scale + 'px'
      });
    };

    BannerUC.prototype.onScreen = function(screen) {
      this.screen = screen;
      return Util.cssPosition(this.$, screen, this.port, this.land);
    };

    BannerUC.prototype.html = function() {
      return "<div   id=\"" + (Util.id('BannerUC')) + "\"   class=\"" + (Util.css('GoBannerUC')) + "\">\n  <div id=\"" + (Util.id('BannerText')) + "\" class=\"" + (Util.css('BannerText')) + "\">GO</div>\n</div>";
    };

    return BannerUC;

  })();

}).call(this);
