// Generated by CoffeeScript 1.9.1
(function() {
  var DealsUC,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  DealsUC = (function() {
    Util.Export(DealsUC, 'uc/DealsUC');

    function DealsUC(stream, role, port, land) {
      this.stream = stream;
      this.role = role;
      this.port = port;
      this.land = land;
      this.callDeals = bind(this.callDeals, this);
      this.setDealData = bind(this.setDealData, this);
      this.gritterId = 0;
      this.uom = 'em';
      this.dealsData = [];
      this.isVisible = false;
    }

    DealsUC.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    DealsUC.prototype.position = function(screen) {
      this.onScreen(screen);
      return this.subscribe();
    };

    DealsUC.prototype.html = function() {
      return "<div id=\"" + (Util.id('DealsUC', this.role)) + "\" class=\"" + (Util.css('DealsUC')) + "\"></div>";
    };

    DealsUC.prototype.show = function() {
      this.isVisible = true;
      return this.$.show();
    };

    DealsUC.prototype.hide = function() {
      this.isVisible = false;
      return this.$.hide();
    };

    DealsUC.prototype.subscribe = function() {
      this.stream.subscribe('Trip', (function(_this) {
        return function(trip) {
          return _this.onTrip(trip);
        };
      })(this));
      this.stream.subscribe('Location', (function(_this) {
        return function(location) {
          return _this.onLocation(location);
        };
      })(this));
      this.stream.subscribe('Screen', (function(_this) {
        return function(screen) {
          return _this.onScreen(screen);
        };
      })(this));
      return this.stream.subscribe('Deals', (function(_this) {
        return function(deals) {
          return _this.onDeals(deals);
        };
      })(this));
    };

    DealsUC.prototype.onTrip = function(trip) {
      return Util.noop('Deals.onTrip()', trip);
    };

    DealsUC.prototype.onLocation = function(location) {
      return Util.noop('DealsUC.onLocation()', this.ext, location);
    };

    DealsUC.prototype.onScreen = function(screen) {
      return Util.cssPosition(this.$, screen, this.port, this.land);
    };

    DealsUC.prototype.latLon = function() {
      return [39.574431, -106.09752];
    };

    DealsUC.prototype.onDeals = function(deals) {
      Util.dbg('DealsUI.onDeals()', deals[0].exit);
      this.popupMultipleDeals('Deals', "for Exit ", "" + deals[0].exit, deals);
      return $('#gritter-notice-wrapper').show();
    };

    DealsUC.prototype.onDeals2 = function(deals) {
      var html;
      return;
      this.$GoDeals.empty();
      html = this.app.deals.goDealsHtml(deals);
      return this.$GoDeals.append(html);
    };

    DealsUC.prototype.onDeals3 = function(deals) {};

    DealsUC.prototype.onConditions = function(conditions) {
      return Util.noop('Deals.onConditions()');
    };

    DealsUC.prototype.getGoDeals = function() {
      return this.dealsData;
    };

    DealsUC.prototype.getNoGoDeals = function() {
      return this.dealsData;
    };

    DealsUC.prototype.getDeals = function() {
      return this.dealsData;
    };

    DealsUC.prototype.setDealData = function(args, deals) {
      return this.dealsData = deals;
    };

    DealsUC.prototype.callDeals = function(args, deals) {
      this.dealsData = deals;
      return this.stream.publish('Deals', deals);
    };

    DealsUC.prototype.popupMultipleDeals = function(title, traffic, eta, deals) {
      var deal, i, len, opts, results;
      opts = this.dealsOptsHtml(title, traffic, eta, deals);
      opts.class_name = "gritter-light";
      opts.sticky = true;
      this.gritter(opts);
      results = [];
      for (i = 0, len = deals.length; i < len; i++) {
        deal = deals[i];
        results.push(this.enableTakeDealClick(deal._id));
      }
      return results;
    };

    DealsUC.prototype.fs = function(size) {
      return size + this.uom;
    };

    DealsUC.prototype.dealsOptsHtml = function(title, traffic, eta, deals) {
      var deal, i, len, opts;
      this.uom = 'em';
      opts = {};
      opts.title = this.dealsTitle(title, 2.0);
      opts.text = this.dealsTrafficEta(traffic, eta, 1.3);
      for (i = 0, len = deals.length; i < len; i++) {
        deal = deals[i];
        opts.text += this.dealHtml(deal, 1.2, true);
      }
      opts.text += "</div>";
      return opts;
    };

    DealsUC.prototype.goDealsHtml = function(deals) {
      var deal, html, i, len;
      this.uom = 'em';
      html = '';
      for (i = 0, len = deals.length; i < len; i++) {
        deal = deals[i];
        html += this.dealHtml(deal, 0.7, false);
      }
      html += "</div>";
      return html;
    };

    DealsUC.prototype.dealsTitle = function(title, fontSize) {
      return "<div style=\"text-align:center;\">\n<div style=\"font-size:" + (this.fs(fontSize)) + ";\">" + title + "</div>";
    };

    DealsUC.prototype.dealsTrafficEta = function(traffic, eta, fontSize) {
      return "<div style=\"font-size:" + (this.fs(fontSize)) + ";\"><span>" + traffic + "</span><span style=\"font-weight:bold;\"> " + eta + "</span></div>";
    };

    DealsUC.prototype.dealHtml = function(deal, fontSize, take) {
      var html, padding, takeSize;
      padding = 0.2 * fontSize;
      takeSize = 0.6 * fontSize;
      html = "<hr  style=\"margin:" + (this.fs(padding)) + "\"</hr>";
      html += "<div style=\"font-size:" + (this.fs(fontSize)) + ";\">" + deal.dealData.name + "</div>\n<div style=\"font-size:" + (this.fs(fontSize)) + ";\"><span>" + deal.dealData.businessName + "</span>" + (this.takeDeal(deal._id, takeSize, padding, take)) + "</div>";
      return html;
    };

    DealsUC.prototype.takeDeal = function(dealId, fontSize, padding, take) {
      var style;
      if (take) {
        style = "font-size:" + (this.fs(fontSize)) + "; margin-left:" + (this.fs(fontSize)) + "; padding:" + (this.fs(padding)) + "; border-radius:" + (this.fs(padding * 2)) + "; background-color:#658552; color:white;";
        return "<span dataid=\"" + dealId + "\" style=\"" + style + "\">Take Deal</span>";
      } else {
        return '';
      }
    };

    DealsUC.prototype.enableTakeDealClick = function(dealId) {
      return $("[dataid=" + dealId + "]").click((function(_this) {
        return function() {
          Util.dbg('Deal.TakeDeal', dealId);
          return _this.stream.publish('TakeDeal', dealId);
        };
      })(this));
    };

    DealsUC.prototype.gritter = function(opts) {
      return $.gritter.add(opts);
    };

    DealsUC.prototype.iAmExiting = function(dataId) {
      return "<div style=\"margin-top:0.5em;\"><span dataid=\"" + dataId + "\" style=\"font-size:0.9em; padding:0.3em; background-color:#658552; color:white;\">I'M EXITING</span></div></div>";
    };

    DealsUC.prototype.deal = function(opts, dataId, gritterId) {
      this.gritter(opts);
      return this.enableIamExitingClick(dataId, gritterId);
    };

    DealsUC.prototype.enableIamExitingClick = function(dataId, gritterId) {
      return $("[dataid=" + dataId + "]").click(function() {
        Util.dbg("I'M EXITING");
        return $.gritter.remove(gritterId);
      });
    };

    return DealsUC;

  })();

}).call(this);
