// Generated by CoffeeScript 1.9.1
(function() {
  var Test;

  Test = (function() {
    var App;

    App = Util.Import('app/App');

    App.Test = Test;

    Util.Export(App.Test, 'app/App.Test');

    function Test(app, stream, simulate, rest, model) {
      this.app = app;
      this.stream = stream;
      this.simulate = simulate;
      this.rest = rest;
      this.model = model;
      Util.log('App.Test.constructor');
      this.subscribe();
    }

    Test.prototype.subscribe = function() {
      return this.stream.subscribe('Trip', (function(_this) {
        return function(trip) {
          return _this.runTrip(trip);
        };
      })(this));
    };

    Test.prototype.runApp = function() {};

    Test.prototype.runStream = function() {};

    Test.runSimulate = function() {};

    Test.prototype.runRest = function() {};

    Test.prototype.runModel = function() {};

    Test.prototype.runTrip = function(trip) {};

    Test.prototype.runSpatial = function() {};

    return Test;

  })();

}).call(this);
