// Generated by CoffeeScript 1.9.1
(function() {
  var Test;

  Test = (function() {
    var App;

    App = Util.Import('app/App');

    App.Test = Test;

    Util.Export(App.Test, 'app/App.Test');

    function Test(simulate, app, stream, rest, model, trip, spatial) {
      this.simulate = simulate;
      this.app = app;
      this.stream = stream;
      this.rest = rest;
      this.model = model;
      this.trip = trip;
      this.spatial = spatial;
    }

    return Test;

  })();

}).call(this);
